services:
  postgres:
    image: postgres:16
    container_name: mentoredu_db
    environment:
      POSTGRES_DB: mentoredu
      POSTGRES_USER: mentoredu
      POSTGRES_PASSWORD: mentoredu
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mentoredu -d mentoredu"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: mentoredu_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mentoredu.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
