services:
  - type: web
    name: mentoredu-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: FRONTEND_BASE_URL
        sync: false
