spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 20000
      initialization-fail-timeout: 60000
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_API_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET}
  mail:
    from: ${MAIL_FROM_ADDRESS:ivanruben.cr@gmail.com}
  frontend:
    base-url: ${FRONTEND_BASE_URL:https://mentoredu-frontend.onrender.com}

cloudinary:
  url: ${CLOUDINARY_URL}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  health:
    mail:
      enabled: false
