spring:
  config:
    import: optional:dotenv:.env
  datasource:
    url: jdbc:postgresql://localhost:5432/mentoredu_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgres
server:
  port: 8080
jwt:
  secret: mentoredu-clave-secreta-super-larga-para-hs256-minimo-32-caracteres
  expiration: 86400000
flyway:
  enabled: true
  locations:
    - classpath:db/migration
    - classpath:/
