@startuml MentorEdu_Containers
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

title MentorEdu System — Level 2: Containers

' === ACTORES ===
Person(visitante, "Visitante", "Usuario no registrado que explora la plataforma o consulta el catálogo público.")
Person(user, "Usuario Autenticado", "Estudiante, Docente, Academia o Administrador con permisos específicos.")

System_Boundary(mentoredu_boundary, "Plataforma MentorEdu") {

    Container(landing, "Landing Page", "HTML, CSS, JS", "Página de presentación de la plataforma, beneficios y pasarela de registro inicial.")

    Container(spa, "Single-Page Application", "Angular", "Interfaz de usuario web interactiva. Gestional el foro, biblioteca, perfiles y ciclo pedagógico.")

    Container(api, "API Application", "Java 21, Spring Boot 3", "Provee la lógica de negocio modularizada por Bounded Contexts (Auth, Profile, Catalog, Library, Forum, Pedagogy, Community) vía API RESTful.")

    ContainerDb(db, "Database", "PostgreSQL 16", "Almacena la información transaccional de usuarios, perfiles, metadatos de recursos, foro, calificaciones y trazas de auditoría.")
}

' === SISTEMAS EXTERNOS ===
System_Ext(cloudinary, "Cloudinary", "Servicio en la nube para el almacenamiento masivo y entrega de archivos PDF de recursos y resoluciones.")
System_Ext(sendgrid, "SendGrid",  "Plataforma externa para el envío de correos transaccionales, alertas de actividad y enlaces de recuperación.")

' === RELACIONES ===
' Accesos de usuarios a las interfaces
Rel(visitante, landing, "Visualiza y se registra en", "HTTPS")
Rel(visitante, spa, "Consulta catálogo público", "HTTPS")
Rel(user, spa, "Usa e interactúa con", "HTTPS")

' Comunicación Front-to-Back
Rel(spa, api, "Consume servicios y envía acciones", "HTTPS/JSON (JWT)")

' Interacciones del Backend (Lógica de Negocio)
Rel(api, db, "Lee y escribe datos en", "JDBC/JPA")
Rel(api, cloudinary, "Sube y recupera documentos PDF", "HTTPS/API REST")
Rel(api, sendgrid, "Solicita envío de emails", "HTTPS/API REST")

@enduml